let books : any = {
    matthew: { abbreviatedBook: "41-MAT", numChapters: 28},
    mark: { abbreviatedBook: "42-MRK", numChapters: 16},
    luke: { abbreviatedBook: "43-LUK", numChapters: 24},
    john: { abbreviatedBook: "44-JHN", numChapters: 21},
    acts: { abbreviatedBook: "45-ACT", numChapters: 28},
    romans: { abbreviatedBook: "46-ROM", numChapters: 16},
    "1-corinthians": { abbreviatedBook: "47-1CO", numChapters: 16},
    "2-corinthians": { abbreviatedBook: "48-2CO", numChapters: 13},
    galatians:  { abbreviatedBook: "49-GAL", numChapters: 6},
    ephesians:  { abbreviatedBook: "50-EPH", numChapters: 6},
    philippians:  { abbreviatedBook: "51-PHP", numChapters: 4},
    colossians: { abbreviatedBook: "52-COL", numChapters: 4},
    "1-thessalonians": { abbreviatedBook: "53-1TH", numChapters: 5},
    "2-thessalonians": { abbreviatedBook: "54-2TH", numChapters: 3},
    "1-timothy": { abbreviatedBook: "55-1TI", numChapters: 6},
    "2-timothy": { abbreviatedBook: "56-2TI", numChapters: 4},
    titus: { abbreviatedBook: "57-TIT", numChapters: 3},
    philemon: { abbreviatedBook: "58-PHM", numChapters: 1},
    hebrews: { abbreviatedBook: "59-HEB", numChapters: 13},
    james: { abbreviatedBook: "60-JAS", numChapters: 5},
    "1-peter": { abbreviatedBook: "61-1PE", numChapters: 5},
    "2-peter": { abbreviatedBook: "62-2PE", numChapters: 3},
    "1-john": { abbreviatedBook: "63-1JN", numChapters: 5},
    "2-john": { abbreviatedBook: "64-2JN", numChapters: 1},
    "3-john": { abbreviatedBook: "65-3JN", numChapters: 1},
    jude: { abbreviatedBook: "66-JUD", numChapters: 1},
    revelation: { abbreviatedBook: "67-REV", numChapters: 22},
}

export {books};